name: whales
channels:
  - conda-forge
dependencies:
  - gdal
  - python<3.12  # don't use the very latest version of python in case wheels aren't made for everything
  - pip
  - pip:
    - bottle>=0.12
    - fiona
    - imageio
    - jupyter
    - mercantile>=1.2
    - numpy
    - opencv-python
    - pandas
    - pyarrow>=15.0.0  # to silence warning from Pandas, can be removed after pandas 3.0
    - pytz
    - rasterio
    - requests
    - requests-auth>=0.6
    - shapely
    - timezonefinder>=6.2
    - torch<2.1  # to account for driver support on my particular system, can be relaxed
    - torch-tb-profiler
    - tqdm
    - utm
