name: whales
channels:
  - conda-forge
dependencies:
  - gdal
  - python<3.12  # don't use the very latest version of python in case wheels aren't made for everything
  - pip
  - pip:
    - bottle>=0.12
    - jupyter
    - mercantile>=1.2
    - pyarrow>=15.0.0  # to silence warning from Pandas, can be removed after pandas 3.0
    - requests
    - requests-auth>=0.6
    - tensorboard>=2.14.1
    - timezonefinder>=6.2
    - torch<2.1  # to account for driver support on my particular system, can be relaxed
    - torch-tb-profiler
    - torchgeo[datasets,docs,style,tests]>=0.5.0
    - utm
